import { useEffect, useCallback } from "react";
import { Loader2, RefreshCw, Sparkles } from "lucide-react";
import { Button } from "@/components/ui/button";
import { MarkdownContent } from "@/components/chat/MarkdownContent";
import { useDiffStore } from "@/stores/diffStore";
import { useWorkspaceStore } from "@/stores/workspaceStore";
import { getTransport } from "@/transport";

/**
 * Format an ISO timestamp as a short relative time string (e.g. "2h ago").
 * Returns "just now" for timestamps within the last minute.
 */
function relativeTime(iso: string): string {
  const diff = Date.now() - new Date(iso).getTime();
  if (!Number.isFinite(diff) || diff <= 0) return "just now";
  const mins = Math.floor(diff / 60_000);
  if (mins < 1) return "just now";
  if (mins < 60) return `${mins}m ago`;
  const hrs = Math.floor(diff / 3_600_000);
  if (hrs < 24) return `${hrs}h ago`;
  const days = Math.floor(diff / 86_400_000);
  return `${days}d ago`;
}

/**
 * Summary tab content for the diff panel.
 *
 * Three states:
 * - Empty: prompt to generate a summary with a CTA button
 * - Loading: spinner while the summary is being generated
 * - Rendered: markdown content with metadata and a regenerate button
 */
export function SummaryView() {
  const activeThreadId = useWorkspaceStore((s) => s.activeThreadId);
  const snapshots = useDiffStore((s) =>
    activeThreadId ? s.snapshotsByThread[activeThreadId] : undefined,
  );
  const hasFileChanges = (snapshots?.length ?? 0) > 0;

  const summaryRecord = useDiffStore((s) => s.summaryRecord);
  const summaryLoading = useDiffStore((s) => s.summaryLoading);
  const setSummaryRecord = useDiffStore((s) => s.setSummaryRecord);
  const setSummaryLoading = useDiffStore((s) => s.setSummaryLoading);

  // Load persisted summary on mount or when the thread changes
  useEffect(() => {
    if (!activeThreadId) return;
    // Skip if already loaded for this thread
    if (summaryRecord?.threadId === activeThreadId) return;

    let cancelled = false;

    const load = async () => {
      try {
        const result = await getTransport().getDiffSummary(activeThreadId);
        if (!cancelled) setSummaryRecord(result);
      } catch {
        if (!cancelled) setSummaryRecord(null);
      }
    };

    void load();
    return () => {
      cancelled = true;
    };
  }, [activeThreadId, summaryRecord?.threadId, setSummaryRecord]);

  const handleGenerate = useCallback(async () => {
    if (!activeThreadId) return;
    setSummaryLoading(true);
    try {
      const result = await getTransport().generateDiffSummary(activeThreadId);
      setSummaryRecord(result);
    } catch {
      // Generation failed; keep the previous state
    } finally {
      setSummaryLoading(false);
    }
  }, [activeThreadId, setSummaryLoading, setSummaryRecord]);

  // Loading state
  if (summaryLoading) {
    return (
      <div className="flex flex-col items-center justify-center gap-2 py-16 text-muted-foreground">
        <Loader2 size={20} className="animate-spin" />
        <span className="text-xs">Generating summary...</span>
      </div>
    );
  }

  // Rendered state
  if (summaryRecord && summaryRecord.threadId === activeThreadId) {
    return (
      <div className="flex flex-col gap-3 p-4">
        <div className="prose prose-sm dark:prose-invert max-w-none text-[13px] leading-relaxed">
          <MarkdownContent content={summaryRecord.content} />
        </div>

        <div className="flex items-center justify-between border-t border-border/30 pt-3">
          <span className="text-[11px] text-muted-foreground">
            Generated by {summaryRecord.model} · {relativeTime(summaryRecord.createdAt)} · Covers{" "}
            {summaryRecord.turnCount} {summaryRecord.turnCount === 1 ? "turn" : "turns"}
          </span>
          <Button
            variant="ghost"
            size="xs"
            onClick={handleGenerate}
            className="gap-1 text-[11px] text-muted-foreground hover:text-foreground"
          >
            <RefreshCw size={12} />
            Regenerate
          </Button>
        </div>
      </div>
    );
  }

  // Empty state
  return (
    <div className="flex flex-col items-center justify-center gap-3 py-16 text-center">
      <Sparkles size={24} className="text-muted-foreground/40" />
      <p className="text-xs text-muted-foreground">
        Generate an AI summary of the changes in this thread
      </p>
      <Button
        variant="outline"
        size="sm"
        onClick={handleGenerate}
        disabled={!hasFileChanges || !activeThreadId}
        className="gap-1.5 text-xs"
      >
        <Sparkles size={12} />
        Generate Summary
      </Button>
    </div>
  );
}
